[package]
name = "lalrpop-calculator"
version = "0.1.0"
authors = ["Vasiliy Yorkin <vasiliy.yorkin@gmail.com>"]
build = "build.rs"

[dependencies]
regex = "0.2"
lalrpop-util = "0.13"

[build-dependencies]
lalrpop = "0.13"